// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpYNDvZ-x4rvQ7RhDWs0fZRvoU6PPTkrY',
    appId: '1:315374225316:web:df9c78a12a43f140106331',
    messagingSenderId: '315374225316',
    projectId: 'gloify-todo',
    authDomain: 'gloify-todo.firebaseapp.com',
    storageBucket: 'gloify-todo.appspot.com',
    measurementId: 'G-CWYM54EQ7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSxv24fiUhCd0OwfjKF1mgTK9ebXCq2x0',
    appId: '1:315374225316:android:089e96d1fee70d5e106331',
    messagingSenderId: '315374225316',
    projectId: 'gloify-todo',
    storageBucket: 'gloify-todo.appspot.com',
  );
}
