// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb1W-n0PQxT8Mos_7CulZxeXzT3eCYIqc',
    appId: '1:470642559463:web:5c46760079472d4fa49542',
    messagingSenderId: '470642559463',
    projectId: 'gliofy-todo',
    authDomain: 'gliofy-todo.firebaseapp.com',
    storageBucket: 'gliofy-todo.appspot.com',
    measurementId: 'G-84L4TNCQCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf2msYoJaKRWusF4vXqFlxhVnS1feSXvo',
    appId: '1:470642559463:android:65fca38ecd0b01b6a49542',
    messagingSenderId: '470642559463',
    projectId: 'gliofy-todo',
    storageBucket: 'gliofy-todo.appspot.com',
  );
}
